# Generated by Django 5.2 on 2025-04-25 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='blog-img/')),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('date_posted', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
